package modeloDatosTPF;
// Generated 31 oct. 2021 21:16:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cultivo generated by hbm2java
 */
@Entity
@Table(name="cultivo"
    ,schema="public"
)
public class Cultivo  implements java.io.Serializable {


     private int id;
     private Suelo suelo;
     private String nombre;
     private Set<Orden> ordens = new HashSet<Orden>(0);
     private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);

    public Cultivo() {
    }

	
    public Cultivo(Suelo suelo, String nombre) {
        this.suelo = suelo;
        this.nombre = nombre;
    }
    public Cultivo(Suelo suelo, String nombre, Set<Orden> ordens, Set<Proyecto> proyectos) {
       this.suelo = suelo;
       this.nombre = nombre;
       this.ordens = ordens;
       this.proyectos = proyectos;
    }
   
     @Id 
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy = IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fksuelo", nullable=false)
    public Suelo getSuelo() {
        return this.suelo;
    }
    
    public void setSuelo(Suelo suelo) {
        this.suelo = suelo;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cultivo")
    public Set<Orden> getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set<Orden> ordens) {
        this.ordens = ordens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cultivo")
    public Set<Proyecto> getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set<Proyecto> proyectos) {
        this.proyectos = proyectos;
    }




}


