package modeloDatosTPF;
// Generated 31 oct. 2021 21:16:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etapaproyecto generated by hbm2java
 */
@Entity
@Table(name="etapaproyecto"
    ,schema="public"
)
public class Etapaproyecto  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set<Orden> ordens = new HashSet<Orden>(0);

    public Etapaproyecto() {
    }

	
    public Etapaproyecto(String nombre) {
        this.nombre = nombre;
    }
    public Etapaproyecto(String nombre, Set<Orden> ordens) {
       this.nombre = nombre;
       this.ordens = ordens;
    }
   
     @Id 
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy = IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etapaproyecto")
    public Set<Orden> getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set<Orden> ordens) {
        this.ordens = ordens;
    }




}


