package modeloDatosTPF;
// Generated 31 oct. 2021 21:16:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lote generated by hbm2java
 */
@Entity
@Table(name="lote"
    ,schema="public"
)
public class Lote  implements java.io.Serializable {


     private int id;
     private Campo campo;
     private Suelo suelo;
     private float superficie;
     private boolean activo;
     private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);

    public Lote() {
    }

	
    public Lote(Campo campo, Suelo suelo, float superficie) {
        this.campo = campo;
        this.suelo = suelo;
        this.superficie = superficie;
        this.activo = true;
    }
    public Lote(Campo campo, Suelo suelo, float superficie, Set<Proyecto> proyectos) {
       this.campo = campo;
       this.suelo = suelo;
       this.superficie = superficie;
       this.activo = true;
       this.proyectos = proyectos;
    }
   
     @Id 
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy = IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkcampo", nullable=false)
    public Campo getCampo() {
        return this.campo;
    }
    
    public void setCampo(Campo campo) {
        this.campo = campo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fksuelo", nullable=false)
    public Suelo getSuelo() {
        return this.suelo;
    }
    
    public void setSuelo(Suelo suelo) {
        this.suelo = suelo;
    }

    
    @Column(name="superficie", nullable=false, precision=8, scale=8)
    public float getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(float superficie) {
        this.superficie = superficie;
    }

    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lote")
    public Set<Proyecto> getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set<Proyecto> proyectos) {
        this.proyectos = proyectos;
    }

   public boolean equals(int i){
        return Objects.equals(this.id, i);
    }


}


