package modeloDatosTPF;
// Generated 31 oct. 2021 21:16:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mineral generated by hbm2java
 */
@Entity
@Table(name="mineral"
    ,schema="public"
)
public class Mineral  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set<Porcentaje> porcentajes = new HashSet<Porcentaje>(0);

    public Mineral() {
    }

	
    public Mineral(String nombre) {
        this.nombre = nombre;
    }
    public Mineral(String nombre, Set<Porcentaje> porcentajes) {
       this.nombre = nombre;
       this.porcentajes = porcentajes;
    }
   
     @Id 
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy = IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mineral")
    public Set<Porcentaje> getPorcentajes() {
        return this.porcentajes;
    }
    
    public void setPorcentajes(Set<Porcentaje> porcentajes) {
        this.porcentajes = porcentajes;
    }




}


