package modeloDatosTPF;
// Generated 31 oct. 2021 21:16:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Porcentaje generated by hbm2java
 */
@Entity
@Table(name="porcentaje"
    ,schema="public"
)
public class Porcentaje  implements java.io.Serializable {


     private int id;
     private Mineral mineral;
     private Suelo suelo;
     private Float cantidad;

    public Porcentaje() {
    }

	
    public Porcentaje(Mineral mineral, Suelo suelo) {
        this.mineral = mineral;
        this.suelo = suelo;
    }
    public Porcentaje(Mineral mineral, Suelo suelo, Float cantidad) {
       this.mineral = mineral;
       this.suelo = suelo;
       this.cantidad = cantidad;
    }
   
     @Id 
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy = IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkminerales", nullable=false)
    public Mineral getMineral() {
        return this.mineral;
    }
    
    public void setMineral(Mineral mineral) {
        this.mineral = mineral;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fksuelo", nullable=false)
    public Suelo getSuelo() {
        return this.suelo;
    }
    
    public void setSuelo(Suelo suelo) {
        this.suelo = suelo;
    }

    
    @Column(name="cantidad", precision=8, scale=8)
    public Float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Float cantidad) {
        this.cantidad = cantidad;
    }




}


