package modeloDatosTPF;
// Generated 31 oct. 2021 21:16:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Situacionanormal generated by hbm2java
 */
@Entity
@Table(name="situacionanormal"
    ,schema="public"
)
public class Situacionanormal  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);

    public Situacionanormal() {
    }

	
    public Situacionanormal(String nombre) {
        this.nombre = nombre;
    }
    public Situacionanormal(String nombre, Set<Proyecto> proyectos) {
       this.nombre = nombre;
       this.proyectos = proyectos;
    }
   
     @Id 
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy = IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="situacionanormal")
    public Set<Proyecto> getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set<Proyecto> proyectos) {
        this.proyectos = proyectos;
    }




}


