package modeloDatosTPF;
// Generated 31 oct. 2021 21:16:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suelo generated by hbm2java
 */
@Entity
@Table(name="suelo"
    ,schema="public"
)
public class Suelo  implements java.io.Serializable {


     private int id;
     private Boolean lagunas;
     private Boolean piedras;
     private Float humedad;
     private Set<Lote> lotes = new HashSet<Lote>(0);
     private Set<Cultivo> cultivos = new HashSet<Cultivo>(0);
     private Set<Porcentaje> porcentajes = new HashSet<Porcentaje>(0);

    public Suelo() {
    }

    public Suelo(Boolean lagunas, Boolean piedras, Float humedad, Set<Lote> lotes, Set<Cultivo> cultivos, Set<Porcentaje> porcentajes) {
       this.lagunas = lagunas;
       this.piedras = piedras;
       this.humedad = humedad;
       this.lotes = lotes;
       this.cultivos = cultivos;
       this.porcentajes = porcentajes;
    }
   
     @Id 
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy = IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="lagunas")
    public Boolean getLagunas() {
        return this.lagunas;
    }
    
    public void setLagunas(Boolean lagunas) {
        this.lagunas = lagunas;
    }

    
    @Column(name="piedras")
    public Boolean getPiedras() {
        return this.piedras;
    }
    
    public void setPiedras(Boolean piedras) {
        this.piedras = piedras;
    }

    
    @Column(name="humedad", precision=8, scale=8)
    public Float getHumedad() {
        return this.humedad;
    }
    
    public void setHumedad(Float humedad) {
        this.humedad = humedad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="suelo")
    public Set<Lote> getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set<Lote> lotes) {
        this.lotes = lotes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="suelo")
    public Set<Cultivo> getCultivos() {
        return this.cultivos;
    }
    
    public void setCultivos(Set<Cultivo> cultivos) {
        this.cultivos = cultivos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="suelo")
    public Set<Porcentaje> getPorcentajes() {
        return this.porcentajes;
    }
    
    public void setPorcentajes(Set<Porcentaje> porcentajes) {
        this.porcentajes = porcentajes;
    }

    public boolean equals(Suelo suelox){
        return Objects.equals(this.id, suelox.getId());
    }


}


